### ISSUE TITLE
Missing icon in about:addons

### ISSUE THREAD

**Issue by pdehaan** [gregglind/addon-wr#16]
After installing temp addon in Firefox Nightly, I see the following in  my about:addons page:

<img width="1131" alt="add-ons_manager" src="https://user-images.githubusercontent.com/557895/33734568-a4ebc9a4-db41-11e7-9f46-c99cf0414dbb.png">

**Comment by pdehaan** [comment]
Ah, my local [generated] install.rdf looks like this, which may explain why I'm seeing missing name/icon:

```xml
    <em:name></em:name>
    <em:description>template shield study to serve a as base.  This one is about Toolbar Buttons</em:description>
    <em:creator>Gregg Lind &lt;glind@mozilla.com&gt;</em:creator>
    <em:iconURL>chrome://whiterose-experience-icons/content/icon.png</em:iconURL>
```

Note that I don't seem to have a "whiterose-experience-icons" directory anywhere, so that may be the cause of missing assets.

**Comment by pdehaan** [comment]
The `<em:name>` is blank because it's copying strings from package.json:

https://github.com/gregglind/addon-wr/blob/526535ea04ce79f59a79381ab71b8c9be61b9af8/package.json#L6-L18

https://github.com/gregglind/addon-wr/blob/526535ea04ce79f59a79381ab71b8c9be61b9af8/templates/install.rdf.mustache#L11

Note that the `addon{}` object doesn't contain a `name` property. Not sure if we can make it more generic `name` so it copies the package.json `name`.

**Comment by gregglind** [comment]
I solved name, but forgot icon.  Will just rip it out probably!

**Comment by gregglind** [comment]
Okay with this, as a wontfix.
