### ISSUE TITLE
Rename generated XPI file instead of creating a sym-link?

### ISSUE THREAD

**Issue by pdehaan** [gregglind/addon-wr#17]
Instead of generating a symbolic link to the generated XPI, why not just do a `mv "${XPI_NAME}" addon.xpi`? (Or even `mv *.xpi addon.xpi`, if the /dist/ directory only has one XPI file)

https://github.com/gregglind/addon-wr/blob/526535ea04ce79f59a79381ab71b8c9be61b9af8/bin/xpi.sh#L39-L49

**Comment by biancadanforth** [comment]
@gregglind , correct me if I am wrong, but I believe one copy (the symlink) is for development, and the other copy is for publishing. There's a naming convention that is adhered to (for tracking in telemetry I assume!), so it's easier to generate this XPI programmatically from details in `package.json` than to manually create it later on.

**Comment by gregglind** [comment]
Correct.  It makes a real one, and a symlink (that always has a predicatble name 'linked-addon.xpi'.  I could change it to be 'copied-addon.xpi'

**Comment by gregglind** [comment]
(this belongs in https://github.com/mozilla/shield-studies-addon-template though :)

**Comment by pdehaan** [comment]
Filed upstream as https://github.com/mozilla/shield-studies-addon-template/issues/42
Closing.
