### ISSUE TITLE
Audit trigger words

### ISSUE THREAD

**Issue by pdehaan** [gregglind/addon-wr#19]
https://github.com/gregglind/addon-wr/blob/16aff7d830938d7c115ae31ade288b1b49155f3c/addon/webextension/background.js#L11

I don’t think “disintigration” is a word. http://www.dictionary.com/misspelling?term=disintigration (me thinks we want “disintegration”, possibly).

Do we want to use "army"? It seems like that could get weird if it's an article about a real live army event on a news site and we inject some styling and tooltips.

Not sure if instead of a string+regex we just do an array of words like this, which gives us a bit more flexibility:

```js
const WORDS = ["dark army", "disintegration", "data", "privacy", "internet", "delete"];
```

**Comment by biancadanforth** [comment]
I've [corrected](https://github.com/gregglind/addon-wr/pull/18/files#diff-3bbd4e468b0ebba9059491d729213dbaR11) the "disintegration" word in the list with my latest PR.

My understanding from @gregglind is that we will receive a list of words from our partners, so these are just a temporary list for now; that said, we can trivially change this as you suggest if needed.

**Comment by gregglind** [comment]
These are coming in a soon patch.

**Comment by pdehaan** [comment]
Closing. Latest strings are in #23 PR.
