### ISSUE TITLE
Audit APPLICABLE_PROTOCOLS

### ISSUE THREAD

**Issue by pdehaan** [gregglind/addon-wr#20]
https://github.com/gregglind/addon-wr/blob/16aff7d830938d7c115ae31ade288b1b49155f3c/addon/webextension/background.js#L141

We were discussing earlier today on Vidyo, but just confirming that we :100: want to modify `ftp:` and `file:` protocols.

**Comment by biancadanforth** [comment]
@pdehaan , do you mean remove them from the list? Can you elaborate?

**Comment by pdehaan** [comment]
@biancadanforth Basically I was just looking for confirmation that we wanted to modify files from `ftp://` and `file://` protocols.

**Comment by gregglind** [comment]
File yes.  That's how we do local testing.
Ftp:  I have no idea of how users can / would even open ftp links!  I think it's safe enough, but if we want to remove it, I have no objection.

**Comment by pdehaan** [comment]
Ref: #23 PR.
