### ISSUE TITLE
hover or click effect on a distorted word

### ISSUE THREAD

**Issue by gregglind** [gregglind/addon-wr#9]
Ideal:  when hovering over a word, have a box with text and a link to sumo.

Simplify:  
1.  hover (or maybe click?) opens a box at "fixed position", or fixed relative to the div?  of known exact size.  Maybe at the lower corner of the span's (el) bounding box?  
2.  once opened, maybe it needs 'click off' to close?
3.  Seriously let's re-use prior work here!  Assume known fonts, sizes, etc.  Nothing fancy!

**Comment by biancadanforth** [comment]
Check out this [codepen](https://codepen.io/biancadanforth/pen/xPNXLo?editors=1111) for a working prototype.
